version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: bachelor-bari-app
    container_name: bachelor-bari-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - bd-network

  web:
    image: nginx:stable
    container_name: bachelor-bari-web
    depends_on:
      - app
    volumes:
      - ./src:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"
    networks:
      - bd-network

  db:
    image: mysql:8.0
    container_name: bachelor-bari-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - bd-network

  composer:
    image: composer:2
    container_name: bd-bachelor-composer
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    command: ["bash", "-lc", "composer install"]
    networks:
      - bd-network

  adminer:
    image: adminer:latest
    container_name: bachelor-bari-adminer
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - bd-network


volumes:
  dbdata:

networks:
  bd-network:
    driver: bridge
